BEGIN;

DROP TYPE IF EXISTS dzien_tygodnia CASCADE;
DROP TYPE IF EXISTS KLASA CASCADE;

DROP TABLE IF EXISTS bilety_miejsce CASCADE;
DROP TABLE IF EXISTS miejsca CASCADE;
DROP TABLE IF EXISTS przedzialy CASCADE;
DROP TABLE IF EXISTS swieta CASCADE;
DROP TABLE IF EXISTS wagony CASCADE;
DROP TABLE IF EXISTS polaczenia_wagony CASCADE;
DROP TABLE IF EXISTS stacje_posrednie CASCADE;
DROP TABLE IF EXISTS polaczenia CASCADE;
DROP TABLE IF EXISTS trasy CASCADE;
DROP TABLE IF EXISTS linie CASCADE;
DROP TABLE IF EXISTS stacje CASCADE;
DROP TABLE IF EXISTS pasazerowie CASCADE;
DROP TABLE IF EXISTS bilety CASCADE;
DROP TABLE IF EXISTS bilety_miejsca CASCADE;
DROP TABLE IF EXISTS ulgi CASCADE;
DROP TABLE IF EXISTS taryfy CASCADE;
DROP TABLE IF EXISTS harmonogramy CASCADE;

COMMIT;
