BEGIN;

DROP TABLE IF EXISTS harmonogramy CASCADE;
DROP TABLE IF EXISTS pasazerowie CASCADE;
DROP TABLE IF EXISTS stacje CASCADE;
DROP TABLE IF EXISTS linie CASCADE;
DROP TABLE IF EXISTS przewoznicy CASCADE;
DROP TABLE IF EXISTS historia_cen CASCADE;
DROP TABLE IF EXISTS polaczenia CASCADE;
DROP TABLE IF EXISTS stacje_posrednie CASCADE;
DROP TABLE IF EXISTS historia_polaczenia CASCADE;
DROP TABLE IF EXISTS bilety CASCADE;
DROP TABLE IF EXISTS przejazdy CASCADE;
DROP TABLE IF EXISTS wagony CASCADE;
DROP TABLE IF EXISTS przedzialy CASCADE;
DROP TABLE IF EXISTS miejsca CASCADE;
DROP TABLE IF EXISTS ulgi CASCADE;
DROP TABLE IF EXISTS bilety_miejsca CASCADE;
DROP TABLE IF EXISTS polaczenia_wagony CASCADE;
DROP TABLE IF EXISTS swieta_stale CASCADE;
DROP TABLE IF EXISTS swieta_ruchome CASCADE;
DROP TABLE IF EXISTS daty_swiat CASCADE;

drop table if exists p_q;
drop table if exists d;
drop table if exists prev;

COMMIT;