DROP FUNCTION sprawdz_harmonogram CASCADE;
DROP FUNCTION sprawdz_ceny CASCADE;
DROP FUNCTION sprawdz_droge CASCADE;
DROP FUNCTION sprawdz_przystanek CASCADE;
DROP FUNCTION sprawdz_polaczenie CASCADE;
DROP FUNCTION sprawdz_zwrot CASCADE;
DROP FUNCTION sprawdz_przejazd CASCADE;
DROP FUNCTION sprawdz_miejsce CASCADE;
DROP FUNCTION sprawdz_date CASCADE;